import Head from 'next/head';
import {BsFillMoonStarsFill} from 'react-icons/bs'
import {AiFillTwitterCircle, AiFillLinkedin, AiFillYoutube} from 'react-icons/ai'

import Image from 'next/image';
import deved from '../public/dev-ed-wave.png';
import code from '../public/code.png';
import consulting from '../public/consulting.png';
import design from '../public/desing.png';

import web1 from '../public/web1.png';
import web2 from '../public/web2.png';
import web3 from '../public/web3.png';
import web4 from '../public/web4.png';
import web5 from '../public/web5.png';

import {useState} from 'react'

export default function Home() {

  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? 'dark' : ''}>
      <Head>
        <title>Eduardo Toro Portafolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
        <section className=' min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-burtons'>developedbyed</h1>
            <ul className='flex items-center'>
              <li><BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className='cursor-pointer text-2xl'/></li>
              <li><a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href='#'>Resume</a></li>
            </ul>
          </nav>
          <div className='text-center p-10 '>
            <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl'>Edixon Toro</h2>
            <h3 className='text-2xl py-2 md:text-3xl'>Developer and programmer.</h3>
            <p className='text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto'>
              Freelancer providing services for programming.
              Join me down below and let's get cracking!
            </p>
          </div>
          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>
            <AiFillTwitterCircle />
            <AiFillLinkedin />
            <AiFillYoutube />            
          </div>
          <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 iflow-hidden md:h-96 md:w-96'>
            <Image src={deved} layout='fill' objectFit='cover'/>
          </div>
        </section>
        
        {/* Second Section */}
        <section>
          <div >
            <h3 className='text-3xl py-1'>Services I offer</h3>
            <p className='text-md py-2 leading-8 text-gray-800'>Sed ut perspiciatis unde omnis iste natus 
              error sit voluptatem accusantium doloremque laudantium, totam rem 
              aperiam, eaque ipsa quae ab illo <span className='text-teal-500'>Agencies </span>inventore veritatis et quasi architecto 
              beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas 
              sit aspernatur aut odit aut fugit,<span className='text-teal-500'>startup </span> sed quia consequuntur magni dolores eos 
              qui ratione voluptatem sequi nesciunt
            </p>
            <p className='text-md py-2 leading-8 text-gray-800'>Sed ut perspiciatis unde omnis iste natus 
              error sit voluptatem accusantium doloremque laudantium, totam rem 
            </p>
          </div>
          
          <div className='lg:flex gap-10'>
          <div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white'>
              <Image className='mx-auto' src={design} width={100} height={100}/>
              <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful Desig</h3>
              <p className='py-2'>
                Creating elegant designs suited for your needs desing theory
              </p>
              <h4 className='py-4 text-teal-600 font-medium'>Desing tool i use</h4>
              <p className='text-gray-800 py-1'>Photoshop</p>
              <p className='text-gray-800 py-1'>Illustritor</p>
              <p className='text-gray-800 py-1'>Figma</p>
            </div>
          </div>

          <div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white'>
              <Image className='mx-auto' src={code} width={100} height={100}/>
              <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful Desig</h3>
              <p className='py-2'>
                Creating elegant designs suited for your needs desing theory
              </p>
              <h4 className='py-4 text-teal-600 font-medium'>Desing tool i use</h4>
              <p className='text-gray-800 py-1'>Photoshop</p>
              <p className='text-gray-800 py-1'>Illustritor</p>
              <p className='text-gray-800 py-1'>Figma</p>
            </div>
          </div>

          <div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white'>
              <Image className='mx-auto' src={consulting} width={100} height={100}/>
              <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful Desig</h3>
              <p className='py-2'>
                Creating elegant designs suited for your needs desing theory
              </p>
              <h4 className='py-4 text-teal-600 font-medium'>Desing tool i use</h4>
              <p className='text-gray-800 py-1'>Photoshop</p>
              <p className='text-gray-800 py-1'>Illustritor</p>
              <p className='text-gray-800 py-1'>Figma</p>
            </div>
          </div>
        </div>
        </section>
        
        <section>
          <div>
            <h3 className='text-3xl py-1'>Portofolio</h3>
          </div>
          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
            <div className='basis-1/3 flex-1'><Image src={web1} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive'/></div>
            <div className='basis-1/3 flex-1'><Image src={web2} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive'/></div>
            <div className='basis-1/3 flex-1'><Image src={web3} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive'/></div>
            <div className='basis-1/3 flex-1'><Image src={web4} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive'/></div>
            <div className='basis-1/3 flex-1'><Image src={web5} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive'/></div>
          </div>
        </section>
      </main>
    </div>
  )
}
